version: '3'
services:
  postgres:
    image: postgres:10.4
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123456789'
      POSTGRES_DB: 'fs'
    command: -p 5432
    ports:
      - "5432:5432"